### PR TITLE
Adding Dockerfile and script to build docker image

### PR DESCRIPTION
**Pull request by leoisl**
Please check if this docker image and the building script is fine or needs improvement (I am providing this build script because for pandora paper I will be building from my fork and from specific branches, but by default it builds from this repo and from master).

TODO: could change base image to alpine, but mummer is not installable with `apk`, so it might be a little bit annoying to get everything set with alpine. That would just shrink the image size though, unsure if we should bother...

### CODE REVIEW

**Comment by martinghunt** [comment]
Thanks for this!

Two things I noticed:
1. I can't see paftools.js getting installed/added to `$PATH` (I think it will be here: /minimap2-2.17_x64-linux/
`misc/paftools.js`)
2. We should run the varifier tests, ie `tox` from the varifier root dir.

I don't have an opinion on shrinking the image size. Is easy to use Ubuntu for the base.

**Comment by leoisl** [comment]
True, will add the tests execution!

I think `paftools.js` will indeed not be found... Forgot about this, in my branch, I changed `setup.py` to install `paftools_fixed.js` (the bugfixed script) with the python files, and call this script instead of `paftools.js` in the `PATH`. I think the best solution would still keep calling `paftools.js` in `PATH`, and submit a bug request and wait for the fix. Also, only my branch actually needs this fix... What do you want us to do?

**Comment by martinghunt** [comment]
I think your suggestion of submit the bug and wait for a fix sounds best, seeing as it only affects your branch.

**Comment by martinghunt** [comment]
👍  looks good. Sorry, hadn't noticed that you're getting the minimap2 release, so paftools.js and k8 already there. I was thinking of git clone, where you don't get them.

**Comment by leoisl** [comment]
In the last commit, the `Dockerfile` actually got simplified, as `paftools.js` and `k8` all come bundled in `minimap2` installation, and are in the `minimap2` dir. So by adding this dir to `PATH`, we got already `paftools.js` and `k8`.

Running `./build_container.sh` (i.e. building from this repo:master) will fail with
```
/bin/sh: 1: tox: not found
```

Thus I added `tox` to `requirements.txt` and running on this docker branch:
```
./build_container.sh https://github.com/leoisl/varifier/ docker
```
works and all the tests pass, so I think the container is now good!

**Comment by leoisl** [comment]
oops, sorry, race condition, did not see your comment before replying!

**Comment by leoisl** [comment]
Argh, I am closing, there is a better way to write this Dockerfile, which I am doing soon

**Comment by mbhall88** [comment]
An alpine image would be best I think. Makes the image much smaller. I can put one together this week if you like?

**Comment by leoisl** [comment]
Yeah, fine by me!! Thanks!!

**Comment by martinghunt** [comment]
Awesome, thanks @mbhall88 !

**Comment by leoisl** [comment]
The other improvement I was thinking about doing, which is the reason I hesitated to merge this, was actually to not make the script build a container from a repo and commit/branch, but build it from the local code. This is not hard to do, I can make after you switch to alpine. I am not experienced with travis, but I think then https://github.com/iqbal-lab-org/varifier/issues/1 reduces to a minimal `.travis.yml` that just tries to run the build-container script, which should try to build the container, and run all tests... although a full and independent `.travis.yml` is not hard to do neither, and it is not a big issue maintaining both the travis and the docker environment... although if `.travis.yml` simply call the script to build the container, then there is just one thing to create and maintain... What do you think?

**Comment by leoisl** [comment]
I am afraid I am trying to overengineer a very simple thing

**Comment by martinghunt** [comment]
I'd prefer a script that installs dependencies, which can then be used by travis, docker, singularity or whatever else.

**Comment by leoisl** [comment]
Then I think it would be good that travis, docker, singularity, whatever use the same base image, so that what travis test is strictly equivalent to the docker/singularity image, which is ultimately what will be used by users? I guess travis is the most restrictive one, allowing only different versions of ubuntu: https://docs.travis-ci.com/user/reference/overview/#linux . I think installing the dependencies on alpine is different from ubuntu (i.e. apt vs apk), so the script might not be totally shareable if we choose alpine for docker, and we could potentially have different builds depending on the software version that is installed by apk and apt? Or maybe the install-deps script should not install anything using a package manager, then it would be fine for all base images?

Although it seems to me that having a single docker image would be enough for everything. In travis, we build and test the docker image, so the CI pipeline is building and testing exactly what users will run with the container. Singularity can pull docker images just fine. The only thing we will need to maintain is the Dockerfile.

**Comment by martinghunt** [comment]
I wouldn't second-guess what a user is going to do ;) Should probably think about conda as well.

I regularly build singularity containers for testing. Maybe I'm an edge case, but I prefer singularity over docker because docker quickly creates a mess filling up my hard drive. I also use vargrant to quickly make a dev environment (I know, could do this with docker/singularity!), so dependencies script is handy for that as well.

I'd take the flexibility of an install script over minimising the size of a docker image.

**Pull request closed without merging**
