### PR TITLE
add dockerfile

### LINKED ISSUE #3: make dockerfile

### PR DESCRIPTION
**Pull request by mbhall88**
closes #3 

Once I have made a conda recipe, then biocontainers will auto-build a container for each release. But I have added this as it might still be useful to have containers for commits in between releases. 

We can setup auto-build on dockerhub whenever there is a commit?

### CODE REVIEW

**Comment by mbhall88** [comment]
See https://hub.docker.com/repository/docker/mbhall88/varifier for a container of the commit in this PR

**Comment by leoisl** [comment]
+1 for auto-build on dockerhub whenever there is a commit (or if you think it is not necessary, only on tagged builds)?

**Comment by martinghunt** [comment]
It runs `pytest` right at the end? Is that arguably better than `tox` because `tox` installs the dependencies inside `.tox` just for the tests, wherease `pytest` will fail if dependencies are not there?

**Comment by martinghunt** [comment]
I'm happy to merge if the tests run (and pass, obv). There's a potential issue at the mo with conda not installing all the `cluster_vcf_records` dependencies. But I think the ones it's missing are not used by varifier anyway.

**Comment by leoisl** [comment]
Oh yeah, sorry, `pytest` run the tests, all good for me!

**Comment by martinghunt** [comment]
Also I just updated `cluster_vcf_records` to read bcf files. To do it requires `bcftools` installed. So that'll need adding. Unless adding it to `conda cluster_vcf_records` means it doesn't need adding here.

**Comment by mbhall88** [comment]
> It runs `pytest` right at the end? Is that arguably better than `tox` because `tox` installs the dependencies inside `.tox` just for the tests, wherease `pytest` will fail if dependencies are not there?

Well, the purpose of `tox` is to test multiple environments. In the case of a container, we only care that the tests pass in the container environment. Also saves having to install tox and all the baggage that comes with tox.

> Also I just updated cluster_vcf_records to read bcf files. To do it requires bcftools installed. So that'll need adding. Unless adding it to conda cluster_vcf_records means it doesn't need adding here.

Ok, if you make a new release of `cluster_vcf_records`, we can add the new bcftools dependency to the conda recipe. Then we can just pin the version of cluster_vcf_records

**Pull request merged**
